FROM elixir:1.5.2-alpine

ENV HOME=/opt/app/ TERM=xterm

# Install basic build dependencies
RUN \
    apk update && \
    apk --no-cache --update add git make g++ && \
    rm -rf /var/cache/apk/*

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /opt/app

ENV MIX_ENV=prod

# Cache elixir deps
RUN mkdir config
COPY config/* config/
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

COPY . .

RUN mix release --env=prod --verbose
